### ISSUE TITLE
Redirect on RequiredAuthProvider

### ISSUE THREAD

**Issue by bnewman-tech** [PropelAuth/react#12]
This might not be the correct location for this question.
I am using RequiredAuthProvider and sometimes it will just go into a loop after logging in on some devices. It will go to localhost then to the propel auth url  and then back. I have tried to clear the cache and cookies, as well as tried incognito browsers and still am unable to successfully load the application on those particular devices.

Is anyone else experiencing this or have any suggestions for troubleshooting?

**Comment by kosciak9** [comment]
I'm experiencing same issue.

**Comment by kosciak9** [comment]
this was my issue :) thanks!

**Comment by bnewman-tech** [comment]
It was an issue with the cookies protection.
