### ISSUE TITLE
Working with subdomains

### ISSUE THREAD

**Issue by rosgoo** [PropelAuth/react#25]
I want my landing page to be at `domain.com` but after logging in, I want to the organization to be the subdomain, like so:
`[orgName].domain.com `
I cannot get PropelAuth to play nicely with this setup in localhost and keep on getting a white screen with a "failed to fetch" error.
I believe this is related to this issue but haven't been able to fix on Chrome: 
https://docs.propelauth.com/overview/faq#i-logged-in-to-my-test-environment-but-my-frontend-doesnt-say-i-m-logged-in

I am also looking at supporting `app.domain.com` in localhost but I think this is the same issue. 

Any advice or setup instructions for this?

**Comment by andrew-propelauth** [comment]
We can definitely help. Usually, we set up custom domains as part of creating a production environment, and then you'd be able to redirect to `domain.com` and have `[orgName].domain.com` make requests successfully. 

In the test environment, we primarily support localhost/vercel.app/workers.dev/ngrok/etc. We haven't yet built the UI flow for setting up a custom domain in the test environment, but it is something we can enable for you.

I just sent you an email asking for some more information and we'll get you set up!
