### ISSUE TITLE
`getActiveOrgFn` doesn't get called when used with `RequiredAuthProvider`

### ISSUE THREAD

**Issue by jtmarmon** [PropelAuth/react#9]
I'm trying to use `useActiveOrg` and I noticed that despite setting a `getActiveOrgFn`, I still don't have an active org returned. Turns out the `getActiveOrgFn` is never called when used with the `RequiredAuthProvider`, only when using the regular `AuthProvider`.

**Comment by andrew-propelauth** [comment]
Thanks for flagging this and providing a fix! The fix is available in v2.0.2
